http.port=8081
http.host=0.0.0.0

service.name=order-service
service.version=1.0

product.service.retry.count=2
product.service.retry.delay=500
payment.service.retry.count=2
payment.service.retry.delay=500

logging.level.root=INFO
logging.level.org.mule=INFO